# Lesson Plan

**This lesson continues our overview of the foundations of pandas.**

## Learning Objectives

- Understand the dataframe object
- Use pandas for basic data manipulation
- Use pandas for basic data visualization

## Revision

Last time we learned about the Series object. A series is:
- A one-dimensional array of indexed data
- Can be created from almost any iterable
- Part dictionary, part list
- Represents a single column of data
- Utilizes vectorized operations

### Revision Questions

1. The following code creates a series. What will be the index values:

  ```python
  
  data = pd.Series([0.25, 0.5, 0.75, 1.0])
  ```

2. The following code creates a series from a dictionary. What will be the index values:

  ```python
  data = pd.Series({'a': 0.25, 'b': 0.5, 'c': 0.75, 'd': 1.0})
  ```
  
3. Each of the following examples accesses the first element of the series. Which one is the correct way to do it?

  ```python
  data[0]
  data['a']
  data.iloc[0]
  data.loc['a']
  ```
  
4. Would any of those examples work with both the labeled and the integer index?

> I think the iloc would work with both the labeled and integer index but not the data['a'] and data.loc['a'] one. Because no such assigned index exists. The first one won't work with the second series of values.

5. Did any of these examples trigger a warning? What was it?

> Answer here

In [1]:
import pandas as pd

In [7]:
#data = pd.Series([0.25, 0.5, 0.75, 1.0])
data = pd.Series({'a': 0.25, 'b': 0.5, 'c': 0.75, 'd': 1.0})
#data[0]
data['a']
data.iloc[0]
data.loc['a']

np.float64(0.25)

## DataFrames
This is where things get really exciting! (I mean they were already, right?)

- The DataFrame is the workhorse of pandas (workpanda?)
- Two-dimensional array with flexible row indices and columns
- Allows us to easily reference and manipulate data on this "grid"

### Creating a DataFrame

You can create data frames from various sources, but recall that, unlike a Series, we need to specify **two dimensions**, which can be represented by a collection of series.

A common pattern is to create a DataFrame from a dictionary where the keys represent the column names and the values represent a series. 

The following figure highlights this relationship:

![by default, a dictionary key maps to a column](images/key_is_col.png)

Have a go at defining your first DataFrame this way:

In [8]:
cities = {
    'population': [
        2.04, 
        5.23, 
        4.96, 
        2.19, 
        1.29
    ], 
    'area': [
        5386, 
        2058, 
        9993, 
        5905, 
        1826
    ]
}

df = pd.DataFrame(cities)

df

   population  area
0        2.04  5386
1        5.23  2058
2        4.96  9993
3        2.19  5905
4        1.29  1826

In [9]:
# notice that the key is transformed to the column, a type we did not have when we learned about a series.
# the closest analogue would be an anonymous series like the one shown below:

population = pd.Series([
        2.04, 
        5.23, 
        4.96, 
        2.19, 
        1.29
    ])

area = pd.Series([5386, 
        2058, 
        9993, 
        5905, 
        1826
    
])
print(population)
print(area)

0    2.04
1    5.23
2    4.96
3    2.19
4    1.29
dtype: float64
0    5386
1    2058
2    9993
3    5905
4    1826
dtype: int64

In [10]:
# In fact, we can create the same DataFrame with those series, like so:

df = pd.DataFrame({ # the {} indicate a dictionary
                'population': population, # notice this time the values are a series, not a list
                'area': area
               })

df

   population  area
0        2.04  5386
1        5.23  2058
2        4.96  9993
3        2.19  5905
4        1.29  1826

#### Applying what we know about Series objects

The DataFrame, as defined previously, isn't very easy to use, what does each row represent?

We could add a third column with the city names, like so:

In [11]:
city_names = ['Perth', 'Sydney', 'Melbourne', 'Brisbane', 'Adelaide']

df = pd.DataFrame({
    "city": city_names,
    "population": population,
    "area": area
})

df

        city  population  area
0      Perth        2.04  5386
1     Sydney        5.23  2058
2  Melbourne        4.96  9993
3   Brisbane        2.19  5905
4   Adelaide        1.29  1826

Hopefully though, you are thinking:

>I'd be much more comfortable if the city was the `index` not just another column

We can do this in a couple of ways, and these ways are shown below. Try uncommenting the different approaches to ensure you understand them:

In [13]:
population = {'Perth': 2.04, 'Sydney': 5.23, 'Melbourne': 4.96, 'Brisbane': 2.19, 'Adelaide': 1.29}
area = {'Perth': 5386, 'Sydney': 2058, 'Melbourne': 9993, 'Brisbane': 5905, 'Adelaide': 1826}

df = pd.DataFrame(cities
, index=city_names)

df

# try this with the population and area series we created earlier, as well as the dictionaries above and see what impact this has on the result.

           population  area
Perth            2.04  5386
Sydney           5.23  2058
Melbourne        4.96  9993
Brisbane         2.19  5905
Adelaide         1.29  1826

The last thing we'll cover is creating a dataframe by explicitly specifying the `columns` and `index`

In [14]:
city_names = ['Perth', 'Sydney', 'Melbourne', 'Brisbane', 'Adelaide']
rows = ['population', 'area']

population_values = [2.04, 5.23, 4.96, 2.19, 1.29]
area_values = [5386, 2058, 9993, 5905, 1826]

df = pd.DataFrame([population_values, area_values], # notice this is a list of lists
                 columns=city_names,
                 index=rows,
                 
                 )

df

              Perth   Sydney  Melbourne  Brisbane  Adelaide
population     2.04     5.23       4.96      2.19      1.29
area        5386.00  2058.00    9993.00   5905.00   1826.00

You are probably a bit disappointed with the result. Understandable. What if you want to treat each list as a column of data? For now, the answer is "tough", unless you use a dictionary, that is. But soon, we'll learn to transpose data; then, it will get really fun!

Okay, here's a preview!

In [15]:
df.T

           population    area
Perth            2.04  5386.0
Sydney           5.23  2058.0
Melbourne        4.96  9993.0
Brisbane         2.19  5905.0
Adelaide         1.29  1826.0

Before we move on to learning how to access the data, recall back to a previous lesson where we saw that the most typical way we'll create large scale DataFrames is from another structured data source, which will often handle a lot of this for us - but we'll still need to understand the fundamental mechanics, so hopefully this exercise was useful to you.

#### Revision exercises

1. **Create a DataFrame from a dictionary**
Use the following code/data to:
    1. Build a dictionary
    2. Load into a datafrom with the columns: 'Student ID', 'Name', and 'Score'

```python
ids = [101, 102, 103]
names = ['Mia', 'Liam', 'Noah']
score = [88, 92, 95]
```

2. **Create a DataFrame from a list of lists**
Use the following code/data to directly load the data into a data set with the columns "'Product', 'Price', 'Quantity'"
```python
data = [['Bread', 3.50, 30], ['Milk', 2.00, 50], ['Eggs', 5.00, 100]]
```

In [44]:
# Your answer here
ids = [101, 102, 103]
names = ['Mia', 'Liam', 'Noah']
score = [88, 92, 95]

df_student = pd.DataFrame({
    "names": names,
    "score": score,
}, index=ids)

df_student



data =[['Bread', 3.50, 30],['Milk', 2.00, 50], ['Eggs', 5.00, 100]]



df = pd.DataFrame(data, columns = ['Products', 'Price', 'Quantity'])

print(df)

  Products  Price  Quantity
0    Bread    3.5        30
1     Milk    2.0        50
2     Eggs    5.0       100

### Accessing data in a DataFrame

Let's work with the DataFrame we created previously. What if we wanted to get just one column? What is a column again...

In [46]:
df = df.T # pivot and remember it

In [47]:
df['population'] # get just the population

KeyError: 'population'

In [46]:
type(df['population'])

pandas.core.series.Series

#### Working with columns means working with a Series

Did you notice what the `type` function returned? That's right, a Series!

You're already an expert with those!

In [52]:
df['population']['Perth'] #?

KeyError: 'population'

Accessing data within a pandas DataFrame is a fundamental skill for data analysis. 

For multiple columns, you pass a list of column names. This returns a **DataFrame**.

```python
# Access 'Name' and 'Age' columns
subset = df[['Name', 'Age']]
```

### Accessing Rows

Rows can be accessed by their position using `.iloc` or by their index using `.loc`.

**Using `.iloc`**:

```python
# Access the first row
first_row = df.iloc[0]

# Access the first three rows
first_three_rows = df.iloc[0:3]
```

**Using `.loc`**:

If your DataFrame has a custom index, you can use `.loc` to access rows by their index labels.

```python
# Access the row with an index label of 'a'
row_a = df.loc['a']
```

### Conditional Selection

To filter data based on conditions, you use conditions inside the selection brackets `[]`.

```python
# Select rows where Age is greater than 25
older_than_25 = df[df['Age'] > 25]
```

### Accessing Specific Values

To get a specific value, combine row and column selections using `.loc` or `.iloc`.

```python
# Using .iloc for row and column position
value = df.iloc[2, 1]  # Third row, second column

# Using .loc for index label and column name
value = df.loc[102, 'Name']  # Row with index 102 and column 'Name'
```

### Summary

- **Select columns** by column name.
- **Slice rows** using `.iloc` for positions or `.loc` for index labels.
- **Filter data** with conditions inside brackets `[]`.
- **Access specific values** using `.loc` or `.iloc` with both row and column selectors.
]

Easy!

#### Exercises

(For the DataFrames, see the code in the next cell)

**Question 1: Selecting Columns**
Given a DataFrame `df` with columns 'Name', 'Age', 'City', and 'Salary', write a command to select and display only the 'Age' and 'Salary' columns.

**Question 2: Slicing Rows**
Assuming you have a DataFrame `df` that contains daily sales data for a week (7 rows), write a command to display only the sales data for the first 3 days.

**Question 3: Conditional Selection**
Given a DataFrame `df` with columns 'Name', 'Age', and 'Department', write a command to select and display rows where the 'Age' is greater than 30 and the 'Department' is 'Marketing'.

**Question 4: Accessing Specific Values**
Consider a DataFrame `df` with columns 'Employee ID', 'Name', and 'Role'. Assuming the DataFrame uses default integer indexing, write a command to access and display the 'Role' of the third employee (index position 2).

**Question 5: Combining Conditions**
With a DataFrame `df` that has columns 'Product', 'Price', and 'Quantity', write a command to select and display rows where 'Price' is less than 10 and 'Quantity' is greater than 50.

**Question 6: Modifying a Specific Value**
Given a DataFrame `df` with columns 'Name', 'Score', and 'Feedback'. Write a command to change the 'Feedback' for the student with a 'Score' of exactly 85 to "Excellent".

**Question 7: Selecting Rows by Index Label**
Assuming a DataFrame `df` has a custom index based on 'Employee ID', write a command to display the row for the employee with ID 102.

In [105]:
# questions 1 and 2:

data = {
    'Name': ['Arpita', 'Sandeep', 'Jordan', 'Chris', 'Pat'],
    'Age': [28, 34, 21, 45, 33],
    'City': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'],
    'Salary': [70000, 80000, 50000, 120000, 90000]
}
df = pd.DataFrame(data)

df[['Salary','Age']]

# question 2 - assumption 
#df.loc[df['Daily sales'] < 3]


# question 3
data = {
    'Name': ['Mia', 'Liam', 'Noah', 'Emma', 'Mitra'],
    'Age': [32, 28, 45, 35, 29],
    'Department': ['IT', 'Marketing', 'HR', 'Marketing', 'IT']
}
df = pd.DataFrame(data)
df.loc[(df['Age'] > 30) & (df['Department'] == 'Marketing')]



# question 4


data = {
    'Employee ID': [101, 102, 103, 104, 105],
    'Name': ['Alex', 'Taylor', 'Jordan', 'Chris', 'Pat'],
    'Role': ['Manager', 'Analyst', 'Clerk', 'Director', 'Assistant']
}
df = pd.DataFrame(data)

value = df.loc[df['Employee ID'] == 103,['Role']]
print(value)


# # question 5

data = {
    'Product': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Marker'],
    'Price': [3, 2.5, 5, 1.5, 8],
    'Quantity': [100, 150, 50, 200, 80]
}
df = pd.DataFrame(data)

df.loc[(df['Price'] < 10) & (df['Quantity'] > 50)]


# question 6

data = {
    'Name': ['Sam', 'Alex', 'Jordan', 'Taylor'],
    'Score': [82, 85, 88, 92],
    'Feedback': ['Good', 'Needs Improvement', 'Very Good', 'Excellent']
}
df = pd.DataFrame(data)


# question 7

data = {
    'Employee ID': [101, 102, 103, 104],
    'Name': ['Alex', 'Taylor', 'Jordan', 'Chris'],
    'Department': ['Sales', 'Marketing', 'HR', 'IT']
}
df_custom_index = pd.DataFrame(data).set_index('Employee ID')

df_custom_index.loc[102]

df_custom_index.loc[102, ['Name', 'Department']]

    Role
2  Clerk

Name             Taylor
Department    Marketing
Name: 102, dtype: str



#### Adding Columns

You can add a new column by  assigning values to it. If you're adding a column that doesn't exist, it will be created.

```python
df['NewColumn'] = [value1, value2, value3]
```

#### Removing Columns

Use `drop` with the `axis=1` parameter to remove columns (the default is `axis=0`, which will remove rows).

```python
df = df.drop('ColumnName', axis=1)
```

#### Adding Rows

To add a single row, you can use the `append` method with a dictionary that represents the new row.

```python
new_row = {'Column1': value1, 'Column2': value2}
df = df.append(new_row, ignore_index=True)
```


#### Removing Rows

Rows can be removed using the `drop` method, specifying the index of the row(s) you wish to remove.

```python
df = df.drop([index])
```

#### Updating Values

You can update a specific value using the `loc` or `iloc` methods to specify the location.

```python
df.loc[row_index, 'ColumnName'] = new_value
```

### Revision Exercises 

**Exercise 1: Adding a New Column**

Given a DataFrame `df` with columns 'Name' and 'Age', add a new column 'Country' with all values set to 'Australia'.

```python

df = pd.DataFrame({'Name': ['Alex', 'Taylor', 'Jordan'],
                   'Age': [25, 30, 22]})
# Add a new column 'Country' with all values 'Australia'
```
df['Country'] = ['Australia','Australia','Australia']

**Exercise 2: Removing a Column**

Given a DataFrame `df`, remove the column 'Age'.

```python
df = pd.DataFrame({'Name': ['Alex', 'Taylor', 'Jordan'],
                   'Age': [25, 30, 22],
                   'City': ['Sydney', 'Melbourne', 'Brisbane']})
# Remove the 'Age' column
```
df = df.drop('Age', axis=1)


**Exercise 3: Adding a Row**

Add a new row to the DataFrame `df`, representing a new employee 'Chris' who is 28 years old and works in 'Design'.

```python
df = pd.DataFrame({'Name': ['Alex', 'Taylor', 'Jordan'],
                   'Age': [25, 30, 22],
                   'Department': ['IT', 'HR', 'Finance']})
# Add a new row for 'Chris', 28, 'Design'
```
new_row = {'Name': 'Chris', 'Age': 28, 'Department': 'Design'}
df = df.append(new_row, ignore_index=True)

**Exercise 4: Removing a Row**

Remove the first row from the DataFrame `df`.

```python
df = pd.DataFrame({'Product': ['Bread', 'Milk', 'Eggs'],
                   'Price': [3.50, 2.00, 5.00]})
# Remove the first row
```
df = df.drop([0])

**Exercise 5: Updating a Value**

Update the 'Price' of 'Milk' to 2.50 in the DataFrame `df`.

```python
df = pd.DataFrame({'Product': ['Bread', 'Milk', 'Eggs'],
                   'Price': [3.50, 2.00, 5.00]})
# Update the price of 'Milk' to 2.50
```
df.loc[df['Product'] == 'Milk', 'Price'] = 2.50 

### Answers

**Exercise 1:**

```python
df['Country'] = 'Australia'
```

**Exercise 2:**

```python
df = df.drop('Age', axis=1)
```

**Exercise 3:**

```python
new_row = {'Name': 'Chris', 'Age': 28, 'Department': 'Design'}
df = df.append(new_row, ignore_index=True)
```

**Exercise 4:**

```python
df = df.drop([0])
```

**Exercise 5:**

```python
df.loc[df['Product'] == 'Milk', 'Price'] = 2.50
```